apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - image: postgres:9.5
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: secret
        - name: POSTGRES_PASSWORD
          value: sentry
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        # volumeMounts:
        # - name: pg-data
        #   mountPath: /var/lib/postgresql/data
        #   subPath: postgres
      restartPolicy: Always
      # volumes:
      # - name: pg-data
      #   persistentVolumeClaim:
      #     claimName: pg-data
status: {}
