apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sentry-worker
  name: sentry-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentry-worker
    spec:
      containers:
      - args:
        - run
        - worker
        envFrom:
          - configMapRef: 
              name: sentry-configmap
        image: sentry:9.1.2
        name: sentry-worker
        resources: {}
      restartPolicy: Always
status: {}
