apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sentry
  name: sentry
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentry
    spec:
      containers:
      - name: sentry
        image: sentry:9.1.2
        envFrom:
          - configMapRef: 
              name: sentry-configmap
        ports:
        - containerPort: 9000
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/lib/sentry/files
          name: sentry
      restartPolicy: Always
      volumes:
      - name: sentry
        persistentVolumeClaim:
          claimName: sentry
status: {}
